apiVersion: v1
kind: Secret
metadata:
  name: cantaloupe-s3
type: Opaque
data:
  s3_endpoint: "{{ .Values.s3.endpoint }}"
  access_key: "{{ .Values.s3.accessKey }}"
  secret_key: "{{ .Values.s3.secretKey }}"
