apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--cantaloupe
  labels:
    {{- include "articleHosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
spec:
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 8182
  selector:
      {{- include "articleHosting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
